controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_product_import:
#    path: /product/csv/import
#    controller: 'App\Controller\ProductController::import'
#    methods: ['POST']

# app_product_download_csv_template:
#    path: /product/csv/download-csv-template
#    controller: 'App\Controller\ProductController::downloadCsvTemplate'
#    methods: ['POST']